org: evancaplan
app: netflix-app-service
service: netflix-app-service

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 128
  apiGateway:
    apiKeys:
      - netflixApiKey

functions:
  findMatchingNetflixEntertainment:
    handler: findMatchingNetflixEntertainment.lambda_handler
    events:
      - http:
          path: search
          method: post
          private: true
  findMediaDetails:
    handler: findMediaDetails.lambda_handler
    events:
      - http:
          path: details
          method: post
          private: true
  uploadUnogsCountry:
    handler: uploadUnogsCountries.lambda_handler
  findCountries:
    handler: findCountries.lambda_handler
    events:
      - http:
          path: countries
          method: get
          private: true