org: evancaplan
app: netflix-search-service
service: netflix-search-service

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 128
  apiGateway:
    apiKeys:
      - netflixSearchApiKey

functions:
  findMatchingNetflixEntertainment:
    handler: findMatchingNetflixEntertainment.lambda_handler
    events:
      - http:
          path: search
          method: post
          private: true
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
  findMediaDetails:
    handler: findMediaDetails.lambda_handler
    events:
      - http:
          path: details
          method: post
          private: true
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
  uploadUnogsCountry:
    handler: uploadUnogsCountries.lambda_handler
  findCountries:
    handler: findCountries.lambda_handler
    events:
      - http:
          path: countries
          method: get
          private: true
          cors:
            origin: '*'
            headers:
              - Content-Type
              - cache-control
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
